### ISSUE TITLE
Code links

### ISSUE THREAD

**Issue by SaviDev** [lostintangent/codeswing#21]
Hi! I dont undestand how connect links.where am i wrong?

`<nav id="menu">
				<ul class="links">
					<li><a href="index.html">Home</a></li>
					<li><a href="swing:portfolio.html">Portfolio</a></li>
					<li><a href="swing:curriculum.html">Curriculum Vitae</a></li>
					<li><a href="contatti.html">Contatti</a></li>
				</ul>
			</nav>`

when I press portfolio or curriculum it doesn't change page.

**Comment by lostintangent** [comment]
Hey! Apologies for the confusion. The swing links are meant to allow you to open a code file within the editor, not to navigate to another page. Are you looking to add a second HTML file to the swing and navigate to it from the main index.html file? If so, I might need to add better support for that, since I don't believe the WebView can navigate to other pages.

**Comment by Rutto17** [comment]
"Are you looking to add a second HTML file to the swing and navigate to it from the main index.html file?" 
Yes, i was trying this method

**Comment by Rutto17** [comment]
Can i have multilple CodeSwing in the same folder? I would create a CodeSwing for a different html inside the same folder of index.html

**Comment by lostintangent** [comment]
Closing this as not planned, since I never heard any other feedback about this behavior.
