### ISSUE TITLE
Export to CodeSandbox

### ISSUE THREAD

**Issue by karlhorky** [lostintangent/codeswing#35]
Hi there,

First of all, thanks for this extension, really amazing! We may end up recommending it to our bootcamp students at @upleveled .

One thing that I thought would be great would be to also be able to export to [CodeSandbox](https://codesandbox.io/). Would you be open to this feature?

**Comment by lostintangent** [comment]
Yeah I'd totally be open to that! I added CodePen support since I was able to find their API, but I haven't investigated CodeSandbox APIs yet. Do you know if they already have support for this?

**Comment by karlhorky** [comment]
Cool! Yeah as far as I know, their API is pretty flexible and allows this kind of use case:

https://codesandbox.io/docs/api

**Comment by lostintangent** [comment]
I'm going to close this as won't fix for now, since I haven't heard any other requests for it, and I'm not sure I want to maintain support for too many export sources. If folks are using CodeSwing regularly, and would benefit a lot from CodeSandbox support, let me know and I'll prioritize this work. Otherwise, the CodePen export support seems to be working great for most users.
