### ISSUE TITLE
Zooming VS Code scales the preview window too

### ISSUE THREAD

**Issue by radiantly** [lostintangent/codeswing#43]
Zooming the VS Code window using `Ctrl+=` or `Ctrl+-` to increase the general interface scale also scales up the preview window. (Ext v0.0.16 on v1.55.2 on Linux).

In retrospect, this might seem obvious, but I think the biggest issue is that the VS Code Interface doesn't mention that it's been zoomed in/out. I've been caught off guard with the actual website turning out to be a scaled version of what I expect.

Ideas on possible fixes:
 - Have a setting that allows you to keep the preview window at 100% regardless of your VS Code scaling (but does anyone really need a scaled version of a website you're prototyping?)
 - If it's not possible to change the preview window scale separately from the interface scale, maybe there can be a warning on the console warning the user that the interface has been scaled, so they aren't caught off-guard.

I've said this before, thank you for this amazing extension!

**Comment by lostintangent** [comment]
Hey! I'm actually not sure if it's possible to have a different zoom factor from the rest of VS Code. I'll investigate this and will discuss what our best options are. Thanks for the feedback!

**Comment by lostintangent** [comment]
Unfortunately, this isn't going to be possible, and I'd be a little worried about displaying a warning message in the console, since many users are using the console for debug/app outcome, and this could be noisy. For now, I'm going to close this as "won't fix", since I'm not aware of a great solution here unfortunately. However, we can listen for more feedback and if necessary, make an ask on VS Code to provide support for this. Thanks!
